windows7/learning_log/learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),
]

windows7/learning_log/learning_logs/urls.py
'''定义learnig_logs的URL模式'''
from django.conf.urls import url

from . import views

urlpatterns =[
    #主页
    url(r'^$',views.index,name='index'),

    #显示所有主题
    url(r'^topics/$',views.topics,name='topics'),
    #特定主体的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),

    #用于添加新主题的网页
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    #用于添加新条目的网页
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

]

windows7/learning_log/pizzeria/pizzeria/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

windows7/learning_log/learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text =models.CharField(max_length=200)
    date_added =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text

class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text =models.TextField()
    date_added =models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ='entries'
    def __str__(self):
        '''返回字符串表示'''
        return self.text[:50] + "..."

windows7/learning_log/test01/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text =models.CharField(max_length=200)
    date_added =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text
class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    data_added=models.DateTimeField(auto_now_add=True)
    class Meta:
        '''嵌套的meta类是为了让entries成为条目名称,管理多个条目.meta存储用于管理模型的额外信息'''
        verbose_name_plural='entries'

    def __str__(self):
        '''返回模型的字符串表示,为了显示效果,取前50个字符友好化显示'''
        return self.text[:50]+'...'

windows7/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic,Entry

from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

windows7/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topic

from .forms import TopicForm,EntryForm

# Create your views here.

def index(request):
    '''学习笔记的主页面'''
    return render(request,'learning_logs/index.html')

def topics(request):
    '''显示所有主题'''
    topics=Topic.objects.order_by('date_added')
    context ={'topics':topics}
    return render(request,'learning_logs/topics.html',context)

def topic(request,topic_id):
    '''显示单个主题及所有条目'''
    topic=Topic.objects.get(id=topic_id)
    entries=topic.entry_set.order_by('-date_added')
    context={'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

def new_topic(request):
    '''添加新主题'''
    if request.method != 'POST':
        #未提交数据，创建一个新表单
        form=TopicForm()
    else:
        #POST提交的数据，对手数据进行处理
        form =TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context ={'form':form}
    return render(request,'learning_logs/new_topic.html',context)


def new_entry(request,topic_id):
    '''在特定的主题中添加新条目'''
    topic=Topic.objects.get(id=topic_id)


    if request.method !='POST':
        #未提交数据，提交一个新表单
        form=EntryForm()
    else:
        #post提交的数据，对数据进行处理
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context={'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

windows7/learning_log/test01/views.py
from django.shortcuts import render

# Create your views here.

windows7/learning_log/learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a>-
	<a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{%block content %}{%endblock content %}

windows7/learning_log/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Learning Log helps you keep track of your learning ,for any topic you 're 
learning adbout.</p>
{% endblock content %}

windows7/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{%block content%}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
  
  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {%csrf_token %}
	{{ form.as_p}}
	<button name="submit">add entry</button>
  </form>
  
{% endblock content%}

windows7/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{%block content%}
  <p>Add a new topic:</p>
  
  <form action="{% url 'learning_logs:new_topic'%}" method='post'>
    {%csrf_token %}
	{{ form.as_p}}
	<button name="submit">add topic</button>
  </form>
  
{% endblock content%}

windows7/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}

  <p>Topic:{{topic}}</p>
  
  <p>Entries:</p>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry:</a>
  </p>
  <ul>
  {% for entry in entries %}
    <li>
	  <p>{{entry.date_added|date:'M d,Y H:i' }}</p>
	  <p>{{ entry.text|linebreaks}}</p>
	</li>
  {% empty %}
    <li>
		There are no entries for this topic yet.
	</li>
  {% endfor %}
  </ul>
  
{% endblock content %}

windows7/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <p>Topics</p>
  
  <ul>
    {% for topic in topics %}
	  <li>
	    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	  </li>
	{% empty %}
	  <li>No topics have been added yet.</li>
	{% endfor %}
  </ul>
  
  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
  
{% endblock content %}

  